function pokedex(){
  var pokemones = [
    {
      "id":"001",
      "name":"Charmander",
      "photo":"01",
      "type":"fire"
    },
    {
      "id":"002",
      "name":"Kanjaskan",
      "photo":"02",
      "type":"fighting"
    },
    {
      "id":"003",
      "name":"Mewtwo",
      "photo":"03",
      "type":"fairy"
    },
    {
      "id":"004",
      "name":"Blastoise",
      "photo":"04",
      "type":"water"
    },
    {
      "id":"005",
      "name":"Bulbasaur",
      "photo":"05",
      "type":"grass"
    },
    {
      "id":"006",
      "name":"Magikarp",
      "photo":"06",
      "type":"water"
    },
    {
      "id":"007",
      "name":"Pikachu",
      "photo":"07",
      "type":"electric"
    },
    {
      "id":"008",
      "name":"Gengar",
      "photo":"08",
      "type":"ghost"
    },
    {
      "id":"009",
      "name":"Vamoacalmarno",
      "photo":"09",
      "type":"water"
    }
  ];

}
